spring.application.name=egov-mdms-legal
server.port=8091
server.servlet.context-path=/egov-legal-mdms

# Local MDMS data
egov.mdms.conf.path=C:/Users/Git_Repoes/Sujog_Git_Collection/od-mdms-data/data

# Master config from Git
masters.config.url=https://raw.githubusercontent.com/PrajwalSamal/egov-mdms-config/main/mdms/legal-master-config.json


# Fail fast on config error
egov.mdms.stopOnAnyConfigError=true
